services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jazzy
    user: jazzer
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./src/:/home/jazzer/workspace/src/
      # - /tmp/.X11-unix:/tmp/.X11-unixs
    tty: true
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  capabilities: [gpu]