# Default initial positions for ur5_robot's ros2_control fake system

initial_positions:
  elbow_joint: 1.7
  shoulder_lift_joint: -2.4
  shoulder_pan_joint: 0
  wrist_1_joint: 0
  wrist_2_joint: 0
  wrist_3_joint: 0